name: Build and deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      digest: ${{ steps.build-and-push.outputs.digest }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/rwx-labs/chadgpt
        tags: |
          type=sha,format=long
          type=edge
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy / Production
    runs-on: ubuntu-latest
    environment: production
    needs:
    - build
    steps:
    - name: Clone deployment repository
      uses: actions/checkout@v4
      with:
        repository: rwx-labs/k8s-rwx-apps
        ssh-key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
    - name: Configure git credentials
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Install mikefarah/yq
      env:
        YQ_VERSION: "v4.35.1"
        YQ_SHA256SUM: "bd695a6513f1196aeda17b174a15e9c351843fb1cef5f9be0af170f2dd744f08"
      run: |
        curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -o yq
        echo "${YQ_SHA256SUM} yq" | sha256sum -c
        install -m0755 ./yq /usr/local/bin/yq
      working-directory: /tmp
    - name: Update chadgpt image tag
      env:
        IMAGE_TAG: ${{ needs.build.outputs.digest }}
      run: |
        yq --version
        yq -i '.helm.parameters[0].value = strenv(IMAGE_TAG)' .argocd-source.yaml

        git add .
        git commit -m "chadgpt: Update to ${IMAGE_TAG}"
        git push
      working-directory: ./chadgpt
